#!/bin/bash

set -e

user="_punssh"
group="_punssh"

dscl=/usr/bin/dscl
$dscl . -read "/Users/${user}" &> /dev/null || {
    # We need to find a free UID/GID
    uid=200
    while $($dscl . -list /Users uid | grep -q "\b${uid}$") || \
        $($dscl . -list /Users gid | grep -q "\b${uid}$"); do
        uid=$((${uid} + 1))
    done
    $dscl . -create /Groups/${group}
    $dscl . -create /Groups/${group} PrimaryGroupID ${uid}
    $dscl . -create /Groups/${group} Password "*"
    $dscl . -create /Groups/${group} RealName "PunSSH Tunnels"
    $dscl . -create /Users/${user}
    $dscl . -create /Users/${user} UserShell /usr/bin/false
    $dscl . -create /Users/${user} NFSHomeDirectory /Library/PunSSH/Home
    $dscl . -create /Users/${user} PrimaryGroupID ${uid}
    $dscl . -create /Users/${user} UniqueID ${uid}
    $dscl . -create /Users/${user} Password "*"
    $dscl . -create /Users/${user} RealName "PunSSH Tunnels"
}

/usr/bin/install -d -m 0755 -o root -g root /Library/PunSSH/Tunnels
/usr/bin/install -d -m 0755 -o ${user} -g ${group} /Library/PunSSH/Home

/bin/launchctl load "/Library/LaunchDaemons/ch.znerol.punssh-defaults.plist"
